import { ProfileButton } from '@/components/profileButton/ProfileButton'
import './globals.css'
import { OptionsModal } from '@/components/options/OptionsModal'
import type { Metadata } from 'next'
import { M_PLUS_Rounded_1c } from 'next/font/google'
import SessionProvider from '@/components/providers/SessionProvider'
import { getServerSession } from 'next-auth'

const M = M_PLUS_Rounded_1c({ subsets: ['latin', 'cyrillic'], weight: ['100', '400', '500', '700', '800', '900'] })

export const metadata: Metadata = {
  title: 'Pomodor',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession()

  return (
    <html lang="en">
      <SessionProvider>
        <body className={`${M.className} min-h-screen`}>
          <div className='max-w-xl px-4 pt-4 mx-auto'>
            <div className='grid grid-cols-2'>
              <h1 className='text-2xl font-medium'>Pomofocus</h1>
              <div className='flex items-center justify-end gap-3'>
                <OptionsModal />
                <ProfileButton />
              </div>
            </div>
            <div className='divider'></div>
          </div>
          <div className='flex items-center justify-center max-w-xl p-6 mx-auto rounded-lg shadow-xl bg-neutral sm:p-14 '>
            {children}
          </div>
        </body>
      </SessionProvider>
    </html>
  )
}
