import { ProfileButton } from '@/components/profileButton/ProfileButton'
import { OptionsModal } from '@/components/options/OptionsModal'
import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'
import SessionProvider from '@/components/providers/SessionProvider'
import { TRPCProvider } from './_trpc/TRPCProvider'
import { headers } from "next/headers";
import { getServerSession } from 'next-auth'
import { TRPCServerClient } from './_trpc/server'
import './globals.css'
import { Toaster } from '@/components/ui/toast/toaster'


const Comfort = Comfortaa({ subsets: ['latin', 'cyrillic'], weight: ['300', '400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Pomodoro',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const hello = await TRPCServerClient.options.hello.query()
  return (
    <html lang="en">
      <TRPCProvider headers={headers()}>
        <SessionProvider>
          <body className={`${Comfort.className} min-h-screen px-2`}>
            <div className='max-w-xl px-4 pt-4 mx-auto'>
              <div className='grid grid-cols-2'>
                <h1 className='text-2xl font-medium'>Pomodoro</h1>
                <div className='flex items-center justify-end gap-3'>
                  <OptionsModal />
                  <ProfileButton />
                </div>
              </div>
              <div className='divider'></div>
            </div>
            {children}

            <Toaster />
          </body>
        </SessionProvider>
      </TRPCProvider>
    </html>
  )
}
